default:
  just --list

IMAGE_NAME := 'speakerbox-training'

# build docker images
build-docker:
	docker build -t {{IMAGE_NAME}} .

# push docker images
# push-docker:

# run docker image locally
run-docker-locally:
  docker run --rm -it {{IMAGE_NAME}} bash