name: Lint, Format, Check

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 23:26:00 UTC (Monday at 15:26:00 PST)
    # We offset from the hour and half hour to go easy on the servers :)
    - cron: '26 23 * * 1'

jobs:
  lint-format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup languages
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    # Install tox
    - name: Install tox
      run: pip install tox
    
    # Run tox / all checks
    - name: Run tox
      run: tox