name: Train Model

on: 
  workflow_dispatch:
    inputs:
      project:
        description: 'Which project directory to move to.'     
        required: true
        default: 'speakerbox' 
        type: choice
        options:
        - speakerbox
      commands:
        description: 'Commands to run to train, eval, etc.'
        required: true 
        type: string

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Test inputs
        run: |
          cd ${{ github.event.inputs.project }}
          ${{ github.event.inputs.commands }}

  #     - name: Deploy runner on EC2
  #       env:
  #         REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         cml runner \
  #             --cloud=aws \
  #             --cloud-region=us-west \
  #             --cloud-type=p2.xlarge \
  #             --labels=cml-gpu
  # train-model:
  #   needs: deploy-runner
  #   runs-on: [self-hosted, cml-gpu]
  #   timeout-minutes: 4320 # 72h
  #   container:
  #     image: docker://iterativeai/cml:0-dvc2-base1-gpu
  #     options: --gpus all
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Train model
  #       env:
  #         REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #       run: |
  #         pip install -r requirements.txt
  #         python train.py

  #         # Create CML report
  #         cat metrics.txt >> report.md
  #         cml publish plot.png --md --title="Confusion Matrix" >> report.md
  #         cml send-comment report.md